spring.application.name=TicketSystem
server.port=${PORT:8080}

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_system
spring.datasource.username=ticket
spring.datasource.password=ticket
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection Pool Properties
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000

# JWT Configuration
jwt.secret='zLwa6FaHb6BdtGaSpbHDxyBiPj9UjtkXE3rqf759IQw4ZylH4WNqK49xg+kP+Ux+ZhWIaTSTac8DhSl4GbtjCA=='
jwt.expiration=86400000

# CORS Configuration
cors.allowed-origins=http://localhost:5173,http://localhost:3000,https://lively-sea-09e22c710.4.azurestaticapps.net
